# Generated by Django 3.0.5 on 2020-04-09 17:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20200409_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='topic_words',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='sentence_text',
            field=models.TextField(),
        ),
    ]
