# Generated by Django 3.0.5 on 2020-04-12 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_auto_20200409_1741'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise',
            new_name='ExerciseSentence',
        ),
    ]
