# Generated by Django 3.0.5 on 2020-04-12 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20200412_2309'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exercisesentence',
            table='exercise_sentences',
        ),
    ]
