# Generated by Django 3.0.5 on 2020-04-13 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_auto_20200412_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_attempts', to='common.User'),
        ),
    ]
